import IProduct from "@/interface/IProduct";

export const products: IProduct[] = [
  // Fresh Fruit
  {
    name: "Green Apple",
    price: 20.285262,
    img: ["greenApple1", "greenApple2", "greenApple3", "greenApple4"],
    category: "Fresh Fruit",
    sale: 50,
    quantity: 1,
    description: `Crisp and tart green apples, perfect for a healthy snack or baking.`,
  },
  {
    name: "Orange",
    price: 10,
    img: ["orange1", "orange2", "orange3", "orange4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Juicy and sweet oranges, great for juicing or eating fresh.`,
  },
  {
    name: "Banana",
    price: 15,
    img: ["banana1", "banana2", "banana3", "banana4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Ripe bananas, perfect for a quick energy boost or smoothies.`,
  },
  {
    name: "Strawberry",
    price: 25,
    img: ["strawberry1", "strawberry2", "strawberry3", "strawberry4"],
    category: "Fresh Fruit",
    sale: 10,
    quantity: 1,
    description: `Sweet and juicy strawberries, ideal for desserts or snacking.`,
  },
  {
    name: "Grapes",
    price: 30,
    img: ["grapes1", "grapes2", "grapes3", "grapes4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Fresh grapes, perfect for snacking or adding to salads.`,
  },
  {
    name: "Blueberries",
    price: 35,
    img: ["blueberries1", "blueberries2", "blueberries3", "blueberries4"],
    category: "Fresh Fruit",
    sale: 15,
    quantity: 1,
    description: `Plump blueberries, ideal for baking or eating fresh.`,
  },
  {
    name: "Watermelon",
    price: 40,
    img: ["watermelon1", "watermelon2", "watermelon3", "watermelon4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Refreshing watermelon, perfect for a hot summer day.`,
  },
  {
    name: "Pineapple",
    price: 50,
    img: ["pineapple1", "pineapple2", "pineapple3", "pineapple4"],
    category: "Fresh Fruit",
    sale: 20,
    quantity: 1,
    description: `Sweet and tangy pineapple, great for snacking or cooking.`,
  },
  {
    name: "Mango",
    price: 60,
    img: ["mango1", "mango2", "mango3", "mango4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Juicy mangoes, perfect for desserts or fresh eating.`,
  },
  {
    name: "Kiwi",
    price: 45,
    img: ["kiwi1", "kiwi2", "kiwi3", "kiwi4"],
    category: "Fresh Fruit",
    quantity: 1,
    description: `Tangy and sweet kiwi, excellent for adding to fruit salads.`,
  }, // Fresh Vegetables
  {
    name: "Cucumber",
    price: 20,
    img: ["cucumber1", "cucumber2", "cucumber3", "cucumber4"],
    category: "Fresh Vegetables",
    sale: 50,
    quantity: 1,
    description: `Fresh cucumbers, perfect for salads or snacking.`,
  },
  {
    name: "Tomato",
    price: 15,
    img: ["tomato1", "tomato2", "tomato3", "tomato4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Juicy tomatoes, ideal for salads, sauces, or fresh eating.`,
  },
  {
    name: "Carrot",
    price: 10,
    img: ["carrot1", "carrot2", "carrot3", "carrot4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Crisp carrots, great for snacking or cooking.`,
  },
  {
    name: "Broccoli",
    price: 25,
    img: ["broccoli1", "broccoli2", "broccoli3", "broccoli4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Fresh broccoli, perfect for steaming or stir-frying.`,
  },
  {
    name: "Bell Pepper",
    price: 30,
    img: ["bellPepper1", "bellPepper2", "bellPepper3", "bellPepper4"],
    category: "Fresh Vegetables",
    sale: 5,
    quantity: 1,
    description: `Crisp bell peppers, great for salads or cooking.`,
  },
  {
    name: "Spinach",
    price: 35,
    img: ["spinach1", "spinach2", "spinach3", "spinach4"],
    category: "Fresh Vegetables",
    sale: 15,
    quantity: 1,
    description: `Fresh spinach, ideal for salads or cooking.`,
  },
  {
    name: "Lettuce",
    price: 20,
    img: ["lettuce1", "lettuce2", "lettuce3", "lettuce4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Crisp lettuce, perfect for salads or sandwiches.`,
  },
  {
    name: "Onion",
    price: 10,
    img: ["onion1", "onion2", "onion3", "onion4"],
    category: "Fresh Vegetables",
    sale: 20,
    quantity: 1,
    description: `Fresh onions, great for cooking or adding to salads.`,
  },
  {
    name: "Garlic",
    price: 15,
    img: ["garlic1", "garlic2", "garlic3", "garlic4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Aromatic garlic, perfect for enhancing flavors in dishes.`,
  },
  {
    name: "Potato",
    price: 10,
    img: ["potato1", "potato2", "potato3", "potato4"],
    category: "Fresh Vegetables",
    quantity: 1,
    description: `Versatile potatoes, great for baking, frying, or mashing.`,
  }, // Meat & Fish
  {
    name: "Chicken Breast",
    price: 50,
    img: [
      "chickenBreast1",
      "chickenBreast2",
      "chickenBreast3",
      "chickenBreast4",
    ],
    category: "Meat & Fish",
    sale: 10,
    quantity: 1,
    description: `Lean chicken breast, perfect for grilling or baking.`,
  },
  {
    name: "Salmon Fillet",
    price: 80,
    img: ["salmonFillet1", "salmonFillet2", "salmonFillet3", "salmonFillet4"],
    category: "Meat & Fish",
    sale: 20,
    quantity: 1,
    description: `Rich and flavorful salmon fillet, ideal for grilling or baking.`,
  },
  {
    name: "Beef Steak",
    price: 100,
    img: ["beefSteak1", "beefSteak2", "beefSteak3", "beefSteak4"],
    category: "Meat & Fish",
    sale: 15,
    quantity: 1,
    description: `Juicy beef steak, perfect for grilling or pan-searing.`,
  },
  {
    name: "Pork Chops",
    price: 60,
    img: ["porkChops1", "porkChops2", "porkChops3", "porkChops4"],
    category: "Meat & Fish",
    quantity: 1,
    description: `Tender pork chops, great for grilling or baking.`,
  },
  {
    name: "Shrimp",
    price: 70,
    img: ["shrimp1", "shrimp2", "shrimp3", "shrimp4"],
    category: "Meat & Fish",
    quantity: 1,
    description: `Fresh shrimp, perfect for grilling, boiling, or adding to dishes.`,
  },
  {
    name: "Lamb Chops",
    price: 90,
    img: ["lambChops1", "lambChops2", "lambChops3", "lambChops4"],
    category: "Meat & Fish",
    quantity: 1,
    description: `Succulent lamb chops, ideal for grilling or roasting.`,
  },
  {
    name: "Cod Fillet",
    price: 75,
    img: ["codFillet1", "codFillet2", "codFillet3", "codFillet4"],
    category: "Meat & Fish",
    quantity: 1,
    description: `Flaky cod fillet, perfect for baking or pan-searing.`,
  },
  {
    name: "Tuna Steak",
    price: 85,
    img: ["tunaSteak1", "tunaSteak2", "tunaSteak3", "tunaSteak4"],
    category: "Meat & Fish",
    sale: 10,
    quantity: 1,
    description: `Firm and flavorful tuna steak, ideal for grilling or searing.`,
  },
  {
    name: "Crab Legs",
    price: 120,
    img: ["crabLegs1", "crabLegs2", "crabLegs3", "crabLegs4"],
    category: "Meat & Fish",
    quantity: 1,
    description: `Sweet and tender crab legs, perfect for a seafood feast.`,
  },
  {
    name: "Beef Ribs",
    price: 110,
    img: ["beefRibs1", "beefRibs2", "beefRibs3", "beefRibs4"],
    category: "Meat & Fish",
    sale: 20,
    quantity: 1,
    description: `Savory beef ribs, great for slow-roasting or barbecuing.`,
  }, // Snacks
  {
    name: "Potato Chips",
    price: 5,
    img: ["potatoChips1", "potatoChips2", "potatoChips3", "potatoChips4"],
    category: "Snacks",
    quantity: 1,
    description: `Crunchy potato chips, perfect for snacking.`,
  },
  {
    name: "Chocolate Bar",
    price: 3,
    img: ["chocolateBar1", "chocolateBar2", "chocolateBar3", "chocolateBar4"],
    category: "Snacks",
    sale: 10,
    quantity: 1,
    description: `Smooth milk chocolate bar, a delightful treat.`,
  },
  {
    name: "Popcorn",
    price: 4,
    img: ["popcorn1", "popcorn2", "popcorn3", "popcorn4"],
    category: "Snacks",
    quantity: 1,
    description: `Buttery popcorn, perfect for movie nights.`,
  },
  {
    name: "Trail Mix",
    price: 6,
    img: ["trailMix1", "trailMix2", "trailMix3", "trailMix4"],
    category: "Snacks",
    sale: 20,
    quantity: 1,
    description: `Healthy trail mix, a balanced snack on the go.`,
  },
  {
    name: "Pretzels",
    price: 3,
    img: ["pretzels1", "pretzels2", "pretzels3", "pretzels4"],
    category: "Snacks",
    quantity: 1,
    description: `Crunchy pretzels, great for dipping or snacking.`,
  },
  {
    name: "Granola Bars",
    price: 2,
    img: ["granolaBars1", "granolaBars2", "granolaBars3", "granolaBars4"],
    category: "Snacks",
    sale: 15,
    quantity: 1,
    description: `Nutritious granola bars, perfect for a quick energy boost.`,
  },
  {
    name: "Cheese Puffs",
    price: 4,
    img: ["cheesePuffs1", "cheesePuffs2", "cheesePuffs3", "cheesePuffs4"],
    category: "Snacks",
    quantity: 1,
    description: `Cheesy and crunchy cheese puffs, a satisfying snack.`,
  },
  {
    name: "Dried Fruit",
    price: 5,
    img: ["driedFruit1", "driedFruit2", "driedFruit3", "driedFruit4"],
    category: "Snacks",
    quantity: 1,
    description: `Sweet and chewy dried fruit mix, a healthy snack option.`,
  },
  {
    name: "Crackers",
    price: 3,
    img: ["crackers1", "crackers2", "crackers3", "crackers4"],
    category: "Snacks",
    sale: 10,
    quantity: 1,
    description: `Light and crispy crackers, perfect with cheese or dips.`,
  },
  {
    name: "Nuts",
    price: 7,
    img: ["nuts1", "nuts2", "nuts3", "nuts4"],
    category: "Snacks",
    quantity: 1,
    description: `Assorted nuts mix, a nutritious snack full of flavor.`,
  }, // Beverages
  {
    name: "Coffee Beans",
    price: 10,
    img: ["coffeeBeans1", "coffeeBeans2", "coffeeBeans3", "coffeeBeans4"],
    category: "Beverages",
    quantity: 1,
    description: `Premium coffee beans, perfect for brewing your favorite cup.`,
  },
  {
    name: "Green Tea",
    price: 5,
    img: ["greenTea1", "greenTea2", "greenTea3", "greenTea4"],
    category: "Beverages",
    sale: 15,
    quantity: 1,
    description: `Refreshing green tea, rich in antioxidants.`,
  },
  {
    name: "Orange Juice",
    price: 3,
    img: ["orangeJuice1", "orangeJuice2", "orangeJuice3", "orangeJuice4"],
    category: "Beverages",
    quantity: 1,
    description: `Freshly squeezed orange juice, packed with Vitamin C.`,
  },
  {
    name: "Mineral Water",
    price: 2,
    img: ["mineralWater1", "mineralWater2", "mineralWater3", "mineralWater4"],
    category: "Beverages",
    quantity: 1,
    description: `Pure mineral water, refreshing and hydrating.`,
  },
  {
    name: "Soda",
    price: 1,
    img: ["soda1", "soda2", "soda3", "soda4"],
    category: "Beverages",
    sale: 10,
    quantity: 1,
    description: `Carbonated soda, a fizzy and refreshing drink.`,
  },
  {
    name: "Coconut Water",
    price: 4,
    img: ["coconutWater1", "coconutWater2", "coconutWater3", "coconutWater4"],
    category: "Beverages",
    quantity: 1,
    description: `Natural coconut water, hydrating and refreshing.`,
  },
  {
    name: "Red Wine",
    price: 20,
    img: ["redWine1", "redWine2", "redWine3", "redWine4"],
    category: "Beverages",
    quantity: 1,
    description: `Smooth red wine, perfect for relaxing evenings.`,
  },
  {
    name: "Apple Cider",
    price: 5,
    img: ["appleCider1", "appleCider2", "appleCider3", "appleCider4"],
    category: "Beverages",
    sale: 20,
    quantity: 1,
    description: `Sweet and tangy apple cider, great for autumn days.`,
  },
  {
    name: "Energy Drink",
    price: 3,
    img: ["energyDrink1", "energyDrink2", "energyDrink3", "energyDrink4"],
    category: "Beverages",
    quantity: 1,
    description: `Refreshing energy drink, boosts energy levels.`,
  },
  {
    name: "Hot Chocolate",
    price: 4,
    img: ["hotChocolate1", "hotChocolate2", "hotChocolate3", "hotChocolate4"],
    category: "Beverages",
    quantity: 1,
    description: `Rich and creamy hot chocolate, perfect for cold days.`,
  }, // Beauty & Health
  {
    name: "Face Cream",
    price: 15,
    img: ["faceCream1", "faceCream2", "faceCream3", "faceCream4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `Moisturizing face cream, nourishes and hydrates skin.`,
  },
  {
    name: "Shampoo",
    price: 10,
    img: ["shampoo1", "shampoo2", "shampoo3", "shampoo4"],
    category: "Beauty & Health",
    sale: 10,
    quantity: 1,
    description: `Gentle shampoo, cleanses hair and scalp effectively.`,
  },
  {
    name: "Conditioner",
    price: 8,
    img: ["conditioner1", "conditioner2", "conditioner3", "conditioner4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `Hydrating conditioner, leaves hair soft and manageable.`,
  },
  {
    name: "Toothpaste",
    price: 5,
    img: ["toothpaste1", "toothpaste2", "toothpaste3", "toothpaste4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `Fluoride toothpaste, protects teeth and freshens breath.`,
  },
  {
    name: "Face Mask",
    price: 12,
    img: ["faceMask1", "faceMask2", "faceMask3", "faceMask4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `Revitalizing face mask, rejuvenates and brightens skin.`,
  },
  {
    name: "Hand Cream",
    price: 8,
    img: ["handCream1", "handCream2", "handCream3", "handCream4"],
    category: "Beauty & Health",
    sale: 15,
    quantity: 1,
    description: `Nourishing hand cream, moisturizes and protects hands.`,
  },
  {
    name: "Sunscreen",
    price: 10,
    img: ["sunscreen1", "sunscreen2", "sunscreen3", "sunscreen4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `SPF 30 sunscreen, protects against UV rays.`,
  },
  {
    name: "Lip Balm",
    price: 3,
    img: ["lipBalm1", "lipBalm2", "lipBalm3", "lipBalm4"],
    category: "Beauty & Health",
    quantity: 1,
    description: `Moisturizing lip balm, prevents dryness and chapping.`,
  },
  {
    name: "Body Lotion",
    price: 12,
    img: ["bodyLotion1", "bodyLotion2", "bodyLotion3", "bodyLotion4"],
    category: "Beauty & Health",
    sale: 20,
    quantity: 1,
    description: `Hydrating body lotion, keeps skin smooth and moisturized.`,
  },
  {
    name: "Vitamin Supplements",
    price: 15,
    img: [
      "vitaminSupplements1",
      "vitaminSupplements2",
      "vitaminSupplements3",
      "vitaminSupplements4",
    ],
    category: "Beauty & Health",
    quantity: 1,
    description: `Multivitamin supplements, supports overall health and wellness.`,
  },
];
